### ISSUE TITLE
Package has CRLF eol

### ISSUE THREAD

**Issue by tempestwood** [tscanlin/css-razor#3]
The current package https://registry.npmjs.org/css-razor/-/css-razor-2.4.0.tgz uses CRLF line ending and the CLI does not run on unix systems. Can you republish it with LF only?

**Comment by tscanlin** [comment]
Yeah, no worries, I just published `2.4.1` from my mac. Can you give that a try and close this out if it's fixed?

**Comment by tempestwood** [comment]
That works. Thanks.
