### ISSUE TITLE
invalid css causes uncaught promise rejection that cannot be caught / is not passed as err object

### ISSUE THREAD

**Issue by tommedema** [tscanlin/css-razor#5]
Consider the following case:

```
const cssRazor = require('css-razor').default

const htmlRaw = '<html><head></head><body></body></html>'
const cssRaw = '<somethingWeirdThatIsNotCss />'

cssRazor({ htmlRaw, cssRaw }, (err, data) => {
  if (err) {
    console.error('razor error!')
    console.error(err)
  }
  
  console.log('razor data')
  console.log(data)
})

process
.on('unhandledRejection', (reason, p) => {
  console.log('unhandled rejection')
  console.error(reason, 'Unhandled Rejection at Promise', p)
})
.on('uncaughtException', err => {
  console.log('uncaught exception')
  console.error(err, 'Uncaught Exception thrown')
  process.exit(1)
})
```

Obviously, this should result in an error, because the passed in css is invalid. However, the callback is never called and `err` is not defined. Therefore it is impossible to deal with a case like this.

What does happen is that an unhandled rejection event is thrown with such data:

```
Toms-MacBook-Pro-2:20171221-cssrazor tommedema$ node example.js 
unhandled rejection
CssSyntaxError {
  name: 'CssSyntaxError',
  reason: 'Unknown word',
  source: '<somethingWeirdThatIsNotCss />',
  line: 1,
  column: 1,
  message: '<css input>:1:1: Unknown word',
  input: { line: 1, column: 1, source: '<somethingWeirdThatIsNotCss />' } } 'Unhandled Rejection at Promise' Promise {
  <rejected> CssSyntaxError {
  name: 'CssSyntaxError',
  reason: 'Unknown word',
  source: '<somethingWeirdThatIsNotCss />',
  line: 1,
  column: 1,
  message: '<css input>:1:1: Unknown word',
  input: { line: 1, column: 1, source: '<somethingWeirdThatIsNotCss />' } } }
```

But this is on a process-scope, and cannot be acted upon. We need to catch such unhandled promise rejections and pass them to `css-razor`'s callback as the `error` object.

**Comment by tommedema** [comment]
By the way, I don't (yet) understand why this is not catched by https://github.com/tscanlin/css-razor/blob/master/index.js#L76, but for some reason it definitely isn't.

**Comment by tommedema** [comment]
Turns out this only happens when you provide a callback. See https://github.com/tscanlin/css-razor/blob/master/index.js#L90 -- you're only handling resolving cases here.

**Comment by tscanlin** [comment]
Thanks for reporting! So would catching that and passing to the callback solve this issue? Or should we handle it some other way?

**Comment by tommedema** [comment]
@tscanlin yes, should do the trick!

```
p
.then(result => callback(null, result))
.catch(err => callback(err))
```

**Comment by tscanlin** [comment]
`2.4.4.` has this fix. Thanks for reporting!
